In [1]:
import torch

### Single value in tensor

In [2]:
torch.tensor(5)

tensor(5)

### Arrays as tensors

In [4]:
val = torch.tensor([1, 2, 3, 4, 5])
val

tensor([1, 2, 3, 4, 5])

In [5]:
val[1]

tensor(2)

In [6]:
val[:3]

tensor([1, 2, 3])

In [7]:
val[2:4]

tensor([3, 4])

In [8]:
revenue = torch.tensor([100, 120, 90, 75])
revenue

tensor([100, 120,  90,  75])

In [9]:
expenses = torch.tensor([80, 117, 71, 68])
expenses

tensor([ 80, 117,  71,  68])

In [10]:
profit =revenue - expenses

profit

tensor([20,  3, 19,  7])

In [12]:
profit_per = profit * 100 / revenue
profit_per

tensor([20.0000,  2.5000, 21.1111,  9.3333])

### Metrices as tensors

In [15]:
# Sales data for Quarter 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = torch.tensor([
    [200, 220, 250],  # Product A (iPhone)
    [150, 180, 210],  # Product B (iPad)
    [300, 330, 360]   # Product C (MacBook)
])

q2 = torch.tensor([
    [209, 231, 259],  # Product A (iPhone)
    [155, 192, 222],  # Product B (iPad)
    [310, 340, 375]   # Product C (MacBook)
])

In [16]:
# total revenue from Q1 and Q2
q1 + q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [17]:
# Revenue growth in Q2 as compared to Q1
q2 - q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [18]:
# % sales units growth in q2 compared to q1

(q2-q1) * 100 / q1

tensor([[4.5000, 5.0000, 3.6000],
        [3.3333, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

### Returned Items

In [19]:
# assume that 10% is the return rate across the board. 
# Find out how many items are returned exactly per product, per region in Q1

return_rate = 0.1
return_rate * q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

* 20 iPhones were returned in USA, 22 in India and 25 in China
* 15 iPads were returned in USA, 18 in India and 21 in China
* 30 Macbooks were returned in USA, 33 in India and 36 in China

In [20]:
return_rate * q2

tensor([[20.9000, 23.1000, 25.9000],
        [15.5000, 19.2000, 22.2000],
        [31.0000, 34.0000, 37.5000]])

In [21]:
# profit per unit is given product and region wise
# calculate total profit for all units per region, per product
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,39]
])

# for this we can use *element wise multiplication*
q1 * profit_per_unit

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [22]:
# for this we can use *element wise multiplication* Q2
q2 * profit_per_unit

tensor([[ 6270,  6237,  6475],
        [ 3100,  3456,  3774],
        [13950, 12920, 14625]])

### Product Revenue

In [23]:
product_prices = torch.tensor([[1100, 450, 1500]])
product_prices

tensor([[1100,  450, 1500]])

In [24]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [25]:
revenue_per_region_matrix = torch.matmul(product_prices, q1)
revenue_per_region_matrix

tensor([[737500, 818000, 909500]])

In [26]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [28]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [29]:
prices_by_region = q1*product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [30]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

### Portfolio Analysis Use Case

In [31]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate)
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [32]:
# Assume that this portfolio is in USD. You want to convert that to INR 
# Assume USD to INR conversion rate to be 83

values_inr = 83*values
values_inr

tensor([[16641.5000, 15438.0000, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

### GPU Acceleration

In [33]:
torch.cuda.is_available()

False

In [34]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU for large-scale customer data processing")
else:
    device = torch.device("cpu")
    print("Using CPU for customer data processing")

Using CPU for customer data processing


In [35]:
# Simulating customer data with 1 million customers and 3 features (age, spending score, income)
customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [36]:
customer_data[:5]

tensor([[0.1161, 0.6968, 0.6137],
        [0.6668, 0.2677, 0.2880],
        [0.1739, 0.8721, 0.3210],
        [0.8520, 0.1373, 0.7744],
        [0.3677, 0.9870, 0.4873]])

In [37]:
high_spending_customers = customer_data[customer_data[:, 1] > 0.5]
high_spending_customers

tensor([[0.1161, 0.6968, 0.6137],
        [0.1739, 0.8721, 0.3210],
        [0.3677, 0.9870, 0.4873],
        ...,
        [0.9602, 0.6250, 0.8021],
        [0.6926, 0.6659, 0.1032],
        [0.8887, 0.7315, 0.9192]])

In [38]:
high_spending_customers.shape

torch.Size([500785, 3])

In [39]:
high_spending_customers_cpu = high_spending_customers.to("cpu")

In [40]:
high_spending_customers_cpu

tensor([[0.1161, 0.6968, 0.6137],
        [0.1739, 0.8721, 0.3210],
        [0.3677, 0.9870, 0.4873],
        ...,
        [0.9602, 0.6250, 0.8021],
        [0.6926, 0.6659, 0.1032],
        [0.8887, 0.7315, 0.9192]])