In [1]:
import numpy as np

In [5]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

## Addition

In [6]:

C = A + B

print(C)

[[ 6  8]
 [10 12]]


## Subtraction

In [8]:
D = B - A

print(D)

[[4 4]
 [4 4]]


## Scalar Multiplication

In [9]:
print(2 * A)


[[2 4]
 [6 8]]


## Element-wise Multiplication

In [10]:
E = A * B

print(E)

[[ 5 12]
 [21 32]]


## Matrix Multiplication

In [11]:
F = A @ B

print(F)

[[19 22]
 [43 50]]


In [12]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [13]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

## Transpose

In [14]:
A.T

array([[1, 3],
       [2, 4]])

In [15]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

## Matrix Power

In [16]:
A * A

array([[ 1,  4],
       [ 9, 16]])

In [19]:
A

array([[1, 2],
       [3, 4]])

In [18]:
np.linalg.matrix_power(A, 2)

array([[ 7, 10],
       [15, 22]])

In [20]:
np.linalg.matrix_power(A, 2)

array([[ 7, 10],
       [15, 22]])