In [1]:
import torch

#### Gradient for a single input

In [5]:
material_cost = torch.tensor(10, requires_grad=True, dtype=torch.float64)
labor_cost = torch.tensor(15, requires_grad=True, dtype=torch.float64)

In [6]:
print(material_cost, labor_cost)

tensor(10., dtype=torch.float64, requires_grad=True) tensor(15., dtype=torch.float64, requires_grad=True)


In [7]:
total_cost = 3 * material_cost**2 + 5*labor_cost + 100
total_cost

tensor(475., dtype=torch.float64, grad_fn=<AddBackward0>)

In [8]:
total_cost.backward()

In [9]:
material_cost.grad, labor_cost.grad

(tensor(60., dtype=torch.float64), tensor(5., dtype=torch.float64))

#### Disable gradient computation

In [17]:
x = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y = x**2 + 5

print("Outside no_grad: ", y.requires_grad)

Outside no_grad:  True


In [18]:
y.backward()
print(x.grad)

tensor(8., dtype=torch.float16)


In [19]:
with torch.no_grad():
    y = x**2 + 5
    print("Inside no_grad: ", y.requires_grad)

Inside no_grad:  False


#### Gradient for a vector

In [ ]:
x = torch.tensor([1,2,3],requires_grad=True,dtype=torch.float16)

y = 2 * x ** 3 + 7 
y

tensor([ 9., 23., 61.], dtype=torch.float16, grad_fn=<AddBackward0>)

In [21]:
result = y.sum()
result

tensor(93., dtype=torch.float16, grad_fn=<SumBackward0>)

In [22]:
result.backward()

In [23]:
x.grad

tensor([ 6., 24., 54.], dtype=torch.float16)

In [24]:
x = torch.tensor([[1,2],[3,4]],requires_grad=True,dtype=torch.float16)

y = 2 * x ** 3 + 7 
y

tensor([[  9.,  23.],
        [ 61., 135.]], dtype=torch.float16, grad_fn=<AddBackward0>)

In [25]:
result = y.sum()
result

tensor(228., dtype=torch.float16, grad_fn=<SumBackward0>)

In [26]:
result.backward()

In [27]:
x.grad

tensor([[ 6., 24.],
        [54., 96.]], dtype=torch.float16)