# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cpu




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [2]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]

tensor_inventory = torch.tensor(inventory)
tensor_inventory

tensor([[12, 15, 10,  0,  5],
        [10,  8,  7,  5,  4],
        [20, 10, 15,  5,  2]])

In [3]:
#2 Find the total inventory for each item across all days
tensor_inventory.sum(dim=0)

tensor([42, 33, 32, 10, 11])

In [7]:
#3 Find the average inventory per day
tensor_inventory.float().mean(dim=1).round()

tensor([ 8.,  7., 10.])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [12]:
#1 Simulate this data using PyTorch's Random Functions
road1 = torch.randint(50, 200, (24,))
road2 = torch.randint(50, 200, (24,))

print(road1)
print(road2)

tensor([115, 136, 113, 168, 139,  82, 130,  50, 162,  91, 186, 182, 173,  59,
        164, 132, 187, 190, 132, 137, 103, 138, 184,  75])
tensor([121, 142, 193, 155,  84, 188, 146, 154, 127, 178, 148, 172, 159, 197,
        102, 164,  52, 163,  95, 157, 141, 144,  61, 181])


In [14]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
print(road1.sum())
print(road2.sum())

tensor(3228)
tensor(3424)


In [15]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
print(road1 + road2)

tensor([236, 278, 306, 323, 223, 270, 276, 204, 289, 269, 334, 354, 332, 256,
        266, 296, 239, 353, 227, 294, 244, 282, 245, 256])




---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [17]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
tensor_weights = torch.tensor([0.8, 1.2, 1.5])
print(tensor_weights)

fitness = torch.tensor([[10, 20, 30],
                        [40, 50, 60],
                        [70, 80, 90]])

weights_fitness = fitness * tensor_weights
weights_fitness


tensor([0.8000, 1.2000, 1.5000])


tensor([[  8.0000,  24.0000,  45.0000],
        [ 32.0000,  60.0000,  90.0000],
        [ 56.0000,  96.0000, 135.0000]])

In [21]:
#2 Find the row-wise and column-wise maximum scores
print(weights_fitness.max(dim=1))  #Row

print(weights_fitness.max(dim=0))  #Col

torch.return_types.max(
values=tensor([ 45.,  90., 135.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([ 56.,  96., 135.]),
indices=tensor([2, 2, 2]))


In [23]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
fitness.t()

tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [42]:
#1 Use PyTorch to compute 'y' for x = 4

x = torch.tensor(4.0, requires_grad=True)

y = 2*x**3 + 5*x**2 - 3*x + 7
print(y)

tensor(203., grad_fn=<AddBackward0>)


In [43]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward(retain_graph=True)

print(x.grad)

tensor(133.)




---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [ ]:
'''
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])
'''

In [31]:
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])

In [32]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)

print(camera1 * camera2)

tensor([[ 5, 12],
        [21, 32]])


In [33]:
#2 Compute Dot Product of the two matrices

print(torch.matmul(camera1,camera2))

tensor([[19, 22],
        [43, 50]])


In [35]:
#3 Compute the Determinant of each matrix
print(torch.det(camera1.float()))
print(torch.det(camera2.float()))

tensor(-2.)
tensor(-2.0000)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [36]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w = torch.tensor(2.0, requires_grad=True)

b = torch.tensor(1.0, requires_grad=True)

x = torch.tensor([1, 2, 3, 4])

print(w)
print(b)
print(x)

tensor(2., requires_grad=True)
tensor(1., requires_grad=True)
tensor([1, 2, 3, 4])


In [44]:
#2 Compute tensors for y
y= w*x + b
print(y)

tensor(9., grad_fn=<AddBackward0>)


In [45]:
y.backward(retain_graph=True)

In [46]:
x.grad

tensor(135.)



---

